### ISSUE TITLE
Error while trying to automatically update data in tableau

### ISSUE THREAD

**Issue by Madhura12gj** [illonage/illonage.github.io#7]
Hi Geraldine,

As I try to extract data from an Instagram business account in Tableau, I get the following error after I try to "Automatically Update" in Tableau. Would appreciate your help in understanding/solving this issue. Thanks!

```
Unexpected Error
Uncaught TypeError: Cannot read property 'length' of undefined   stack:TypeError: Cannot read property 'length' of undefined
    at Object.success (https://illonage.github.io/instagram.js:300:38)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2:27244)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2:28057)
    at x (https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:4:21843)
    at HTMLScriptElement.b.onload.b.onreadystatechange (https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:4:26934)
Error Code:95BE3012
```

**Comment by saketl7** [comment]
Did you get any update or other way to solve this issue?
